/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <fakemeta>
#include <xs>
#include <hamsandwich>

#define PLUGIN "New Plug-In"
#define VERSION "1.0"
#define AUTHOR "author"

public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	register_event("23", "Spray", "a", "1=112")
	
	//register_forward(FM_CmdStart, "fw_CmdStart", 1)
	
	//set_task(120.0, "Advertise", .flags = "b")
}

public Advertise()
{
	client_print(0, print_chat, "[SPRAY DISTANCE] CrazyRussian Stole this idea from a server. All thank him.")
}
/*
public fw_CmdStart(id, uc_handle, seed)
{
	if(get_uc(uc_handle, UC_Buttons) & IN_USE && !(pev(id, pev_oldbuttons) & IN_USE))
		Spray(id)
}*/

public Spray()
{
	new id = read_data(2)
	
	new Float:vOrigin[3], iSprayOrigin[3]
	
	get_user_origin(id, iSprayOrigin, 3)
	pev(id, pev_origin, vOrigin)
	
	if(!(pev(id, pev_flags) & FL_ONGROUND))
	{
		client_print(id, print_chat, "Not on ground")
		
		new Float:vGroundOrigin[3]
		xs_vec_copy(vOrigin, vGroundOrigin)
		
		vGroundOrigin[2] = -9999.0
		
		new hTr = create_tr2()
		engfunc(EngFunc_TraceLine, vOrigin, vGroundOrigin, DONT_IGNORE_MONSTERS, id, hTr)
		
		new Float:flFraction
		get_tr2(hTr, TR_flFraction, flFraction)
		
		if( flFraction == 1.0 )
		{
			free_tr2(hTr)
			client_print(id, print_chat, "[SPRAY] Error determining ground origin")
			return;
		}
		
		//new Float:vPlane[3]
		get_tr2(hTr, TR_vecEndPos, vGroundOrigin)
		//get_tr2(hTr, TR_vecPlaneNormal, vPlane)
		
		//server_print("%0.2f %0.2f %0.2f .... %0.2f %0.2f %0.2f", vPlane[0], vPlane[0], vPlane[0], vGroundOrigin[0], vGroundOrigin[1], vGroundOrigin[2])
		
		//vGroundPosition
		new Float:flMins[3]//, Float:flMaxs[3]
		pev(id, pev_mins, flMins)
		//pev(id, pev_maxs, flMaxs)
		
		vGroundOrigin[2] += (flMins[2] * -1)
		
		xs_vec_copy(vGroundOrigin, vOrigin)
		//server_print("%0.2f %0.2f %0.2f .... %0.2f %0.2f %0.2f", vPlane[0], vPlane[0], vPlane[0], vGroundOrigin[0], vGroundOrigin[1], vGroundOrigin[2])
	}
	
	new Float:vSprayOrigin[3]
	for(new i; i < 3; i++)
	{
		vSprayOrigin[i] = float(iSprayOrigin[i])
	}
	
	client_print(0, print_chat, "Distance to spray from ground: %0.2f", get_distance_f(vOrigin, vSprayOrigin))
}
