#define SJ_BALL_ENTITY_NAME "sj_ball"
#define MAX_HINTTEXT_LENGTH 128
#define LASER_SPRITE "sprites/laserbeam.vmt"
#define MAX_FILENAME_LENGTH 64
#define MAX_FUNCTION_NAME_LENGTH 32

const int TEAMS_COUNT = 4;

#define DISTANCE_BETWEEN_PLAYER_AND_BALL 55.0

#define BALL_HOLD_HEIGHT 15
#define BALL_KICK_HEIGHT_ADDITION 15
#define BALL_TRAIL_TIME 3.0

#define BASE_HP 70
#define BASE_SPEED 250.0
#define BASE_DISARM 10
#define DISARM_MULTIPLIER 3
#define BALL_SPEED_FAST 600.0

#define MAX_TEAMPLAY_LEVEL 3
#define TEAMPLAY_KICK_STRENGTH_ADDITION 100